module: L10n-swift
author: Adrian Bobrowski
author_url: https://github.com/Decybel07
github_url: https://github.com/Decybel07/L10n-swift
root_url: https://decybel07.github.io/L10n-swift/

clean: true
theme: fullwidth
skip_undocumented: true
readme: README.md

output: docs
